In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report,multilabel_confusion_matrix,roc_auc_score,roc_curve

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [6]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [7]:
df['Species']=df['Species'].replace({'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2})

In [8]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [9]:
df['Species'].value_counts()

0    50
1    50
2    50
Name: Species, dtype: int64

In [10]:
df.drop(['Id'],axis=1,inplace=True)

In [11]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [12]:
x=df.drop(['Species'],axis=1)
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [13]:
y=df['Species']

In [14]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1,stratify=y)
x_train


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
21             5.1           3.7            1.5           0.4
47             4.6           3.2            1.4           0.2
141            6.9           3.1            5.1           2.3
90             5.5           2.6            4.4           1.2
64             5.6           2.9            3.6           1.3
..             ...           ...            ...           ...
41             4.5           2.3            1.3           0.3
93             5.0           2.3            3.3           1.0
26             5.0           3.4            1.6           0.4
3              4.6           3.1            1.5           0.2
42             4.4           3.2            1.3           0.2

[120 rows x 4 columns]

In [16]:
y_test.value_counts()

2    10
0    10
1    10
Name: Species, dtype: int64

In [17]:
y_train

21     0
47     0
141    2
90     1
64     1
      ..
41     0
93     1
26     0
3      0
42     0
Name: Species, Length: 120, dtype: int64

In [18]:
clf_model=LogisticRegression(multi_class='ovr')
clf_model.fit(x_train,y_train)

LogisticRegression(multi_class='ovr')

In [19]:
y_pred=clf_model.predict(x_test)
y_pred

array([2, 0, 1, 0, 0, 0, 2, 2, 2, 1, 0, 1, 2, 1, 2, 0, 2, 1, 1, 2, 1, 1,
       0, 0, 2, 1, 0, 0, 2, 1], dtype=int64)

In [20]:
y_test

107    2
9      0
98     1
11     0
43     0
0      0
148    2
111    2
121    2
76     1
16     0
53     1
112    2
62     1
113    2
15     0
102    2
71     1
57     1
127    2
74     1
66     1
37     0
8      0
147    2
106    2
5      0
12     0
56     1
54     1
Name: Species, dtype: int64

In [21]:
y_pred_prob=clf_model.predict_proba(x_test)

In [22]:
y_pred_train=clf_model.predict(x_train)

In [23]:
test_accuracy=accuracy_score(y_test,y_pred)
training_accuracy=accuracy_score(y_train,y_pred_train)
print('Train Accuracy:-',training_accuracy)
print('Test Accuracy:-',test_accuracy)

Train Accuracy:- 0.9583333333333334
Test Accuracy:- 0.9333333333333333


In [24]:
clf_report=classification_report(y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      0.90      0.90        10
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



In [25]:
y_pred_prob=clf_model.predict_proba(x_test)
y_pred_prob

array([[3.61965026e-05, 3.41589378e-01, 6.58374426e-01],
       [7.87974999e-01, 2.12022695e-01, 2.30633454e-06],
       [3.26510816e-01, 6.71338722e-01, 2.15046192e-03],
       [8.50466721e-01, 1.49529750e-01, 3.52954463e-06],
       [9.13091357e-01, 8.69001472e-02, 8.49539420e-06],
       [8.97258003e-01, 1.02739864e-01, 2.13294200e-06],
       [5.94589898e-04, 1.56423895e-01, 8.42981515e-01],
       [4.64713312e-04, 3.74118772e-01, 6.25416515e-01],
       [2.03589538e-03, 4.10344609e-01, 5.87619496e-01],
       [3.41040014e-03, 5.84837290e-01, 4.11752310e-01],
       [9.63676918e-01, 3.63207683e-02, 2.31387402e-06],
       [2.81405526e-02, 9.17277183e-01, 5.45822644e-02],
       [2.76924380e-04, 2.46468518e-01, 7.53254558e-01],
       [2.53203623e-02, 9.42989792e-01, 3.16898459e-02],
       [1.02033811e-03, 4.49214344e-01, 5.49765318e-01],
       [9.84935673e-01, 1.50608361e-02, 3.49136696e-06],
       [9.16214104e-05, 2.56830786e-01, 7.43077593e-01],
       [5.00623019e-02, 8.69746

In [26]:
y_pred_prob[:,1]

array([0.34158938, 0.21202269, 0.67133872, 0.14952975, 0.08690015,
       0.10273986, 0.1564239 , 0.37411877, 0.41034461, 0.58483729,
       0.03632077, 0.91727718, 0.24646852, 0.94298979, 0.44921434,
       0.01506084, 0.25683079, 0.8697466 , 0.80116929, 0.39401915,
       0.80568186, 0.70241355, 0.21202269, 0.26565653, 0.27645809,
       0.72365605, 0.04921396, 0.23102726, 0.43808605, 0.63202813])

In [27]:
x_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
107            7.3           2.9            6.3           1.8
9              4.9           3.1            1.5           0.1
98             5.1           2.5            3.0           1.1
11             4.8           3.4            1.6           0.2
43             5.0           3.5            1.6           0.6
0              5.1           3.5            1.4           0.2
148            6.2           3.4            5.4           2.3
111            6.4           2.7            5.3           1.9
121            5.6           2.8            4.9           2.0
76             6.8           2.8            4.8           1.4
16             5.4           3.9            1.3           0.4
53             5.5           2.3            4.0           1.3
112            6.8           3.0            5.5           2.1
62             6.0           2.2            4.0           1.0
113            5.7           2.5            5.0           2.0
15             5.7           4.4            1.5           0.4
102            7.1           3.0            5.9           2.1
71             6.1           2.8            4.0           1.3
57             4.9           2.4            3.3           1.0
127            6.1           3.0            4.9           1.8
74             6.4           2.9            4.3           1.3
66             5.6           3.0            4.5           1.5
37             4.9           3.1            1.5           0.1
8              4.4           2.9            1.4           0.2
147            6.5           3.0            5.2           2.0
106            4.9           2.5            4.5           1.7
5              5.4           3.9            1.7           0.4
12             4.8           3.0            1.4           0.1
56             6.3           3.3            4.7           1.6
54             6.5           2.8            4.6           1.5

In [29]:
x_test.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
107            7.3           2.9            6.3           1.8
9              4.9           3.1            1.5           0.1
98             5.1           2.5            3.0           1.1
11             4.8           3.4            1.6           0.2
43             5.0           3.5            1.6           0.6

In [30]:
clf_model.predict(x_test.head())

array([2, 0, 1, 0, 0], dtype=int64)

In [31]:
df.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [38]:
x_test.iloc[1:2]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
9            4.9           3.1            1.5           0.1

In [47]:
clf_model.predict([[4,5,5,7]])[0]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


2

In [37]:
clf_model.predict(x_test.iloc[1:2])[0]

0

In [59]:
def predict_class(SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm):
    prediction = clf_model.predict([[SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm]])
    print(f'Predcited class is {prediction}')
    return prediction[0]


In [60]:
predict_class(4,5,5,7)

Predcited class is [2]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


2